CREATE TABLE historial_movimiento
(
    id_movimiento INTEGER NOT NULL,
    product_id    INTEGER,
    tipo          VARCHAR(255),
    cantidad      INTEGER NOT NULL,
    fecha         VARCHAR(255),
    user_id       INTEGER,
    CONSTRAINT pk_historialmovimiento PRIMARY KEY (id_movimiento)
);

CREATE TABLE producto
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre          VARCHAR(255),
    descripcion     VARCHAR(255),
    categoria       VARCHAR(255),
    precio          FLOAT   NOT NULL,
    cantidad        INTEGER NOT NULL,
    cantidad_minima INTEGER NOT NULL,
    eliminado       BOOLEAN NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE usuario_roles
(
    usuario_id INTEGER NOT NULL,
    roles      VARCHAR(255)
);

ALTER TABLE historial_movimiento
    ADD CONSTRAINT FK_HISTORIALMOVIMIENTO_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES producto (id);

ALTER TABLE historial_movimiento
    ADD CONSTRAINT FK_HISTORIALMOVIMIENTO_ON_USER FOREIGN KEY (user_id) REFERENCES usuario (id);

ALTER TABLE usuario_roles
    ADD CONSTRAINT fk_usuario_roles_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id);