drop table historial_movimiento;

CREATE TABLE historial_movimiento
(
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    INTEGER,
    tipo          VARCHAR(255),
    cantidad      INTEGER NOT NULL,
    fecha         VARCHAR(255),
    user_id       INTEGER,
    CONSTRAINT pk_historialmovimiento PRIMARY KEY (id_movimiento)
);